GameStore/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GameStore.Models;
using GameStore.Models.Entity;

namespace GameStore.Controllers
{
    [Authorize(Roles ="admin")]
    public class AdminController : Controller
    {
        private Context db = new Context();

        // GET: Admin
        public ActionResult Index()
        {
            return View(db.Games.Include(m => m.Categories).ToList());
        }

        private MultiSelectList GetCategories(int[] selectedValues)
        {
           // var categories = db.Categories.OrderBy(m => m.Name).Select(m => new { m.CategoryId, m.Name }).ToList();
            var categories = (from m in db.Categories select new { m.CategoryId, m.Name }).ToList();
            var list = new MultiSelectList(categories, "CategoryId", "Name", selectedValues);
            return list;
        }

        // GET: Admin/Create
        public ActionResult Create()
        {
            ViewBag.Categories = GetCategories(null);
            return View();
        }

        // POST: Admin/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "GameId,Name,Description,Category,Price")] Game game, int[] categories)
        {
            if (ModelState.IsValid)
            {
                foreach(var catId in categories)
                {
                    game.Categories.Add(db.Categories.Find(catId));
                }
                db.Games.Add(game);
                db.SaveChanges();
                TempData["message"] = string.Format("Игра \"{0}\" была успешно занесена в базу", game.Name);
                return RedirectToAction("Index");
            }
            ViewBag.Categories = GetCategories(categories);
            return View(game);
        }

        // GET: Admin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var game = db.Games.Include(m => m.Categories).FirstOrDefault(m => m.GameId == id);
            if (game == null)
            {
                return HttpNotFound();
            }
            var categoriesGame = game.Categories.Select(m => m.CategoryId).ToArray();
            ViewBag.Categories = GetCategories(categoriesGame);
            return View(game);
        }

        // POST: Admin/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "GameId,Name,Description,Category,Price")] Game game, int[] categories)
        {
            if (ModelState.IsValid)
            {
                var newGame = db.Games.Include(m => m.Categories).First(m=> m.GameId==game.GameId);
                newGame.Name = game.Name;
                newGame.Description = game.Description;
                newGame.Price = game.Price;

                newGame.Categories.Clear();
                if (categories != null)
                {
                    foreach (var cat in db.Categories.Where(m => categories.Contains(m.CategoryId)))
                    {
                        newGame.Categories.Add(cat);
                    }
                }
                db.Entry(newGame).State = EntityState.Modified;
                db.SaveChanges();
                TempData["message"] = string.Format("Изменения в игре \"{0}\" были сохранены", game.Name);
                return RedirectToAction("Index");
            }
            ViewBag.Categories = GetCategories(categories);
            return View(game);
        }

        // GET: Admin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Games.Include(m => m.Categories).FirstOrDefault(m => m.GameId==id);
            if (game == null)
            {
                return HttpNotFound();
            }
            return View(game);
        }

        // POST: Admin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Game game = db.Games.Find(id);
            db.Games.Remove(game);
            db.SaveChanges();
            TempData["message"] = string.Format("Игра \"{0}\" была успешно удалена", game.Name);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GameStore/Controllers/CartController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using GameStore.Models;
using GameStore.Models.Person;
using System.Data.Entity;
using GameStore.Models.Entity;
using GameStore.Models.Cart;

namespace GameStore.Controllers
{
    [Authorize(Roles = "user")]
    public class CartController : Controller
    {
        private Context db = new Context();

        public ViewResult Index(string returnUrl)
        {
            int id = User.Identity.GetUserId<int>();
            IEnumerable<Order> ordersUser = db.Orders.Where( m => m.UserId == id).Include(m => m.Game);
            var model = new CartInfo(ordersUser, returnUrl);
            return View(model);
        }
      
        public PartialViewResult Summary(string returnUrl)
        {
            int id = User.Identity.GetUserId<int>();
            IEnumerable<Order> ordersUser = db.Orders.Where(m => m.UserId == id).Include(m => m.Game);
            var model = new CartInfo(ordersUser, returnUrl);
            return PartialView(model);
        }

        [HttpPost]
        public RedirectToRouteResult AddToCart(int gameId, string returnUrl)
        {
            var game = db.Games.FirstOrDefault(m => m.GameId == gameId);
            var user = db.Users.Find(User.Identity.GetUserId<int>());

            var order = db.Orders.Create();
            order.Game = game;
            order.User = user;
            db.Orders.Add(order);
            db.SaveChanges();

            return RedirectToAction("Index", new { returnUrl });
        }

        [HttpPost]
        public RedirectToRouteResult RemoveFromCart(int gameId, string returnUrl)
        {

            var game = db.Games.FirstOrDefault(m => m.GameId == gameId);
            if (game != null)
            {
                int id = User.Identity.GetUserId<int>();
                var order = db.Orders.Where(m => m.GameId == game.GameId && m.UserId == id);
                if (order != null)
                {
                    db.Orders.RemoveRange(order);
                    db.SaveChanges();
                }
                db.SaveChanges();
            }
            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

GameStore/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GameStore.Models;
using GameStore.Models.Entity;
namespace GameStore.Controllers
{
    public class NavController : Controller
    {
        Context db = new Context();

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.category = category;

            var cat = db.Categories.ToList();

            cat.Insert(0, new Category { Name = "Все" });

            return PartialView(cat);
        }
    }
}

GameStore/Views/Shared/GameSummary.cshtml
@model GameStore.Models.Entity.Game
@using GameStore.Models.Person

<div class="form-group well">
    <h2>
        @Html.DisplayFor(m => m.Name)
        <span class="pull-right label label-primary">
            @Html.DisplayFor(m => m.Price)
        </span>
    </h2>
    @if (User.Identity.IsAuthenticated && !User.Identity.GetUserRole().Equals("admin"))
    {
        using (Html.BeginForm("AddToCart", "Cart", new { gameId = Model.GameId, returnUrl = Request.Url.PathAndQuery }))
        {
            <div class="pull-right">
                <input type="submit" class="btn btn-success" value="Добавить в корзину" />
            </div>
        }
    }
    <p class="lead">
        @Html.DisplayFor(m => Model.Description)
    </p>
</div>

GameStore/Views/Shared/Profile.cshtml
@using GameStore.Models.Person;

<ul class="nav navbar-nav navbar-right">
    @if (User.Identity.IsAuthenticated)
    {
        <li>
            @Html.ActionLink(User.Identity.Name,"#")
        </li>
        <li>
             @Html.ActionLink("Logout", "Logout", "Account")
        </li>
        if (User.Identity.GetUserRole().Equals("admin"))
        {
            @Html.ActionLink("К БАЗЕ", "Index", "Admin",
    new { returnUrl = Request.Url.PathAndQuery },
    new { @class = "btn btn-default navbar-btn" })
        }
        else
        {
            @Html.Action("Summary", "Cart");
        }
    }
    else
    {
        <li>
            @Html.ActionLink("Registration", "Registr", "Account")
        </li>
        <li>
            @Html.ActionLink("Login", "Login", "Account")
        </li>
    }
</ul>

GameStore/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/chosen")
    @RenderSection("scripts", required: false)

</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
  
</body>
</html>

GameStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">GameStore - магазин компьютерных игр</a>
            </div>
            <div class="navbar-collapse collapse">
                @Html.Partial("Profile")
            </div>
        </div>
    </div>
    <div class="panel">
        <div id="categories" class="col-xs-3">
            @Html.Action("Menu", "Nav")

        </div>
        <div class="container body-content col-xs-8">
            @RenderBody()
        </div>
    </div>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
</body>
</html>