GameStore/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GameStore.Models;
using GameStore.Models.Pagina;
using System.Data.Entity;
using GameStore.Models.Entity;

namespace GameStore.Controllers
{
    public class GameController : Controller
    {
        // GET: Game
        public ActionResult List( string category, int page =1)
        {
            int countItemPerPage = 3;
            int totalItem;
            IEnumerable<Game> games = null;
            using (Context db = new Context())
            {
                games = db.Games.Include(m => m.Categories);
                if (!String.IsNullOrEmpty(category) && !category.Equals("Все"))
                {
                    games = db.Categories.Where(m => m.Name.Equals(category)).Include(m => m.Games).SelectMany(m => m.Games);
                }
                totalItem = games.Count();
                games = games.Skip((page - 1) * countItemPerPage).Take(countItemPerPage).ToList();
            }
            PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = countItemPerPage, TotalItem = totalItem };
            GamesList model = new GamesList { Category = category, PageInfo = pageInfo, Games = games };

            return View(model);
        }

        
    }
}

GameStore/Views/Admin/Create.cshtml
@model GameStore.Models.Entity.Game
@{
    ViewBag.Title = "Админ панель: внесение товара в базу";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<div class="panel">
    <div class="panel-heading">
        <h2>Внесение игры в Базу</h2>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="panel-body">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", rows = 5 })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Categories, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="editor-field">
                    @Html.ListBox("Categories", ViewBag.Categories as MultiSelectList,
                   new { @class = "chzn-select", data_placeholder = "Выберите категорию...", style = "width:350px;" })
                </div>
                @Html.ValidationMessageFor(model => model.Categories, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="panel-footer">
            <input type="submit" value="Сохранить" class="btn btn-primary" />
            @Html.ActionLink("Отменить изменения и вернуться к списку", "Index", null, new
       {
           @class = "btn btn-default"
       })
        </div>
    }
</div>
<script>$(".chzn-select").chosen(); </script>

GameStore/Views/Admin/Delete.cshtml
@{
    ViewBag.Title = "Админ панель: удаление товара";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel">
    <div class="panel-heading">
        <h3></h3>
    </div>
    @model GameStore.Models.Entity.Game

    @{
        ViewBag.Title = "Delete";
        Layout = "~/Views/Shared/_AdminLayout.cshtml";
    }

    <h2>Удаление игры «@Model.Name»</h2>

    <h3>Вы уверены, что хотите ее удалить?</h3>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Categories)
            </dt>

            <dd>
                <ul class="nav navbar-nav">
                    @foreach (var cat in Model.Categories)
                    {
                        <li class="navbar-text">@cat.Name</li>
                    }
                </ul>

            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="panel-footer">
                <input type="submit" value="Удалить" class="btn btn-primary" />
                @Html.ActionLink("Вернуться к списку", "Index", null, new
       {
           @class = "btn btn-default"
       })
            </div>


        }
    </div>
    </div>

GameStore/Views/Admin/Edit.cshtml
@model GameStore.Models.Entity.Game

@{
    ViewBag.Title = "Админ панель: редактирование товара";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="panel">
    <div class="panel-heading">
        <h2>Редактирование игры «@Model.Name»</h2>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="panel-body">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.GameId)

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.TextAreaFor(model => model.Description, new { @class = "form-control", rows = 5 })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Categories, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.ListBox("Categories", ViewBag.Categories as MultiSelectList,
                   new { @class = "chzn-select", data_placeholder = "Выберите категорию...", style = "width:350px;" })
                @Html.ValidationMessageFor(model => model.Categories, "", new { @class = "text-danger" })
            </div>
            

            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="panel-footer">
            <input type="submit" value="Сохранить" class="btn btn-primary" />
            @Html.ActionLink("Отменить изменения и вернуться к списку", "Index", null, new
       {
           @class = "btn btn-default"
       })
        </div>
    }
</div>
<script>$(".chzn-select").chosen(); </script>

GameStore/Views/Admin/Index.cshtml
@model IEnumerable<GameStore.Models.Entity.Game>

@{
    ViewBag.Title = "Админ панель: список товаров";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<style>
    #cartTable td {
        vertical-align: middle;
    }
</style>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Список игр</h3>
         @Html.ActionLink("Вернуться к сайту", "List", "Game", new { returnUrl = Request.Url.PathAndQuery }, new { @class = "btn btn-default" })
    </div>
    
    <div class="panel-body">
        <table id="cartTable" class="table table-striped table-condensed table-bordered">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Categories)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th class="text-center">Действия</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.ActionLink(item.Name, "Edit", new { id = item.GameId, @class = "text-left" })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description, new { @class = "text-left" })
                    </td>
                    <td>
                        <ul class="nav navbar-nav">
                            @foreach (var cat in item.Categories)
                            {
                                <li class="navbar-text">@cat.Name</li>
                            }
                        </ul>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price, new { @class = "text-right" })
                    </td>
                    <td>
                        @Html.ActionLink("Delete", "Delete", new { id = item.GameId })
                    </td>
                </tr>
            }
        </table>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Добавить игру", "Create", null,
            new { @class = "btn btn-default" })
    </div>
</div>